import type { Metadata } from "next";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import Providers from './providers'
import "@fontsource/fustat/400.css"; // weight 400 (regular)
import "@fontsource/fustat/700.css"; // weight 700 (bold)
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="[font-size:16px]">
      <body
        className={`font-fustat antialiased`}
      >
        <div className="min-h-screen bg-white">
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>

        </div>
      </body>
    </html>
  );
}
